let {view, move, fade_in, fade_out, invert, change_view, start} = window.preji;

var title = view("title").set_scale(1);
var svg = view("svg");
var regex = view("regex");
var prog = view("prog1");
var nonterm = view("nonterm").set_scale(1.3);
var accel = view("accel").set_scale(1.02);
var prog_accelerated = view("prog-accelerated");
var prog_final = view("prog-final");
var invariants = view("invariants").set_scale(1.02);
var experiments = view("experiments").set_scale(1.3);

var move_loop_cond_g = move("loop-cond-g", "loop-cond-g-moved");

var slides = [
    [
        fade_out([
            "prog-final",
            "prog-accelerated",

            "bs",
            "transition-abc",
            "nonterm1",
            "nonterm2",
            "closed-y",
            "closed-x",
            "simple-inv-def",
            "simple-inv-ex",
            "cond-inv-def",
            "md-def",
            "md-ex1",
            "md-ex2",
            "psi-def",
            "phi-si-1",
            "phi-si-s",
            "phi-md-1",
            "phi-md-2",
            "phi-md-s",
            "phi-ci-1",
            "phi-ci-s",
            "timeline",
            "si-premise",

            "prog-loop-label-f-accelerated",
            "prog-final-state",
            "loop-accelerated",
            "nondet",
            "nondet-moved",
            "nonterm-cond-substituted",
            "prog-transition-final",
            "sat",
            "loop-cond-f-hard",
            "loop-cond-g-hard",
            "loop-cond-g-moved",

            "inv-nm",
            "inv-template",
            "inv-template-ex",
            "inv-hard-soft",
            "inv-sat",
            "inv-simple",
            "inv-progress",
            "inv-local",
            "inv-nonterm",
            "inv-fast",
            "inv-sol-ex",
            "inv-res-ex",
            "inv-ex-simple",
            "inv-ex-progress",

            "experiments-its",
            "experiments-anant",
            "experiments-c",
        ], duration=0),
        change_view(title, delay=0, slowdown=0),
    ],
    [change_view(svg)],
    [change_view(regex)],
    [fade_in(["bs"])],
    [fade_in(["transition-abc"]), fade_out(["state-f", "transition-a", "transition-b", "transition-c"])],
    [change_view(svg)],
    [change_view(prog)],
    [change_view(svg)],
    [change_view(nonterm)],
    [fade_in(["nonterm1"])],
    [fade_in(["nonterm2"])],
    [change_view(svg)],
    [change_view(prog)],
    [fade_in(["prog-final-state"]), fade_out(["loop-assign-g", "prog-nonterm-loop"]), move_loop_cond_g],
    [change_view(svg)],
    [change_view(accel)],
    [fade_in(["closed-y"])],
    [fade_in(["closed-x"])],
    [fade_in(["psi-def"])],
    [fade_in(["cond-inv-def"])],
    [fade_in(["simple-inv-def"])],
    [fade_in(["simple-inv-ex"])],
    [fade_in(["md-def"])],
    [fade_in(["timeline"])],
    [fade_in(["phi-si-1"])],
    [fade_in(["phi-si-s"])],
    [fade_in(["phi-md-1"])],
    [fade_in(["md-ex1"])],
    [fade_in(["si-premise"])],
    [fade_in(["md-ex2"])],
    [fade_in(["phi-md-2"])],
    [fade_in(["phi-md-s"])],
    [fade_in(["phi-ci-1"])],
    [fade_in(["phi-ci-s"])],
    [fade_in(["loop-accelerated"])],
    [change_view(svg)],
    [change_view(prog)],
    [change_view(prog_accelerated), fade_in(["prog-loop-label-f-accelerated"]), fade_out(["loop-cond-f"])],
    [fade_in(["nondet"])],
    [move("nondet", "nondet-moved")],
    [fade_out(["loop-cond-g"]), fade_in(["nonterm-cond-substituted"])],
    [
        change_view(prog_final),
        fade_out(["nonterm-cond-substituted", "prog-loop-label-f-accelerated", "prog-state-f", "prog-transition-start-f", "prog-transition-f-g", "prog-loop-f"]),
        fade_in(["prog-transition-final"]),
        invert(move_loop_cond_g),
    ],
    [fade_in(["sat"])],
    [
        change_view(prog),
        fade_out(["nondet", "sat", "prog-transition-final", "prog-final-state"]),
        fade_in(["prog-state-f", "prog-transition-start-f", "prog-transition-f-g", "loop-cond-g", "prog-nonterm-loop", "loop-assign-g", "loop-cond-f", "prog-loop-f"])
    ],
    [fade_out(["loop-cond-g", "loop-cond-f"]), fade_in(["loop-cond-g-hard", "loop-cond-f-hard"])],
    [change_view(svg)],
    [change_view(invariants)],
    [fade_in(["inv-template"])],
    [fade_in(["inv-template-ex"])],
    [fade_in(["inv-nm"])],
    [fade_in(["inv-hard-soft"])],
    [fade_in(["inv-sat"])],
    [fade_in(["inv-simple"])],
    [fade_in(["inv-progress"])],
    [fade_in(["inv-local"])],
    [fade_in(["inv-nonterm"])],
    [fade_in(["inv-fast"])],
    [fade_in(["inv-sol-ex"])],
    [fade_in(["inv-res-ex"])],
    [fade_in(["inv-ex-simple"])],
    [fade_in(["inv-ex-progress"])],
    [change_view(svg)],
    [change_view(experiments)],
    [fade_in(["experiments-its"])],
    [fade_in(["experiments-anant"])],
    [fade_in(["experiments-c"])],
    [change_view(svg)],
];

// start the presentation
start(slides);
